//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Birthday.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Birthday
    {
        public Birthday()
        {
            this.ContactBirthdates = new HashSet<ContactBirthdate>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> LatActivityDate { get; set; }
    
        public virtual ICollection<ContactBirthdate> ContactBirthdates { get; set; }
    }
}
